---

test_default_conf:
  DEFAULT:
    debug: "{{ test_log_debug }}"
    log_dir: "{{ test_log_file | dirname }}"
    log_file: "{{ test_log_file | basename }}"

  testcase:
    timeout: "{{ test_case_timeout }}"
    test_runner_timeout: "{{ test_runner_timeout }}"

  tripleo:
    undercloud_ssh_hostname: "{{ undercloud_ssh_hostname }}"
    overcloud_ssh_username: "{{ overcloud_ssh_username }}"

test_log_debug: false

test_case_timeout: 1800.
test_runner_timeout: 14400.

# OpenStack client credentials
stackrc_file: '{{ ansible_user_dir }}/overcloudrc'

undercloud_hostname: '{{ groups.get("undercloud", []) | first | default("undercloud-0") }}'
undercloud_ssh_hostname: ''

overcloud_ssh_username: ''
