---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
        args: [--allow-multiple-documents, --unsafe]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: requirements-txt-fixer
        args:
          - doc/requirements.txt
          - extra-requirements.txt
          - infrared_plugin/requirements.txt
          - linters-requirements.txt
          - requirements.txt
          - test-requirements.txt
          - upper-constraints.txt
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/flake8.git
    rev: '3.8.4'  # pick a git hash / tag to point to
    hooks:
      - id: flake8
        additional_dependencies: [flake8-import-order]
        files: ^tobiko/

  - repo: https://github.com/pre-commit/mirrors-mypy.git
    rev: 'v0.931'
    hooks:
      - id: mypy
        files: ^tobiko/
        entry: mypy --install-types --non-interactive tobiko/
        pass_filenames: false
        # args: [--ignore-missing-imports]

  - repo: https://github.com/ansible/ansible-lint.git
    rev: v4.2.0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: .tox/pep8/bin/pylint
        files: ^tobiko/
        language: system
        types: [python]

#  - repo: https://github.com/adrienverge/yamllint.git
#    rev: v1.23.0
#    hooks:
#      - id: yamllint
#        files: \.(yaml|yml)$

#  - repo: https://opendev.org/openstack/bashate.git
#    rev: 2.0.0
#    hooks:
#      - id: bashate
