---

test_workflow_steps:
  - tox_description: 'create Neutron resources'
    tox_envlist: neutron
    tox_step_name: create_neutron_resources
    tox_environment:
      TOBIKO_PREVENT_CREATE: no

  - tox_description: 'run disruptive test cases'
    tox_envlist: neutron_faults
    tox_step_name: neutron_faults

  - tox_description: 'verify Neutron resources'
    tox_envlist: neutron
    tox_step_name: verify_neutron_resources
    tox_environment:
      TOBIKO_PREVENT_CREATE: yes
