---

test_workflow_steps:
  - tox_description: 'run sanity test cases before creating resources'
    tox_envlist: neutron_sanity
    tox_step_name: before
    tox_environment:
      TOBIKO_PREVENT_CREATE: no

  - tox_description: 'create Neutron resources'
    tox_envlist: neutron
    tox_step_name: create_neutron_resources
    tox_environment:
      TOBIKO_PREVENT_CREATE: no

  - tox_description: 'run disruptive test cases (neutron)'
    tox_envlist: neutron_faults
    tox_step_name: neutron_faults
    pytest_maxfail: 1

  - tox_description: 'run disruptive test cases (high availability)'
    tox_envlist: ha_faults
    tox_step_name: ha_faults
    pytest_maxfail: 1

  - tox_description: 'run sanity test cases after disruptive tests'
    tox_envlist: neutron_sanity
    tox_step_name: after
    tox_environment:
      TOBIKO_PREVENT_CREATE: no

  - tox_description: 'verify Neutron resources'
    tox_envlist: neutron
    tox_step_name: verify_neutron_resources
    tox_environment:
      TOBIKO_PREVENT_CREATE: yes
