---

test_workflow_steps:
  - tox_description: 'run sanity test cases before creating resources'
    tox_envlist: sanity
    tox_step_name: before
    tox_environment:
      TOBIKO_PREVENT_CREATE: no

  - tox_description: 'create workload resources'
    tox_envlist: scenario
    tox_step_name: create_resources
    tox_environment:
      TOBIKO_PREVENT_CREATE: no

  - tox_description: 'run disruptive test cases'
    tox_envlist: faults
    tox_step_name: faults
    tox_environment:
      TOBIKO_PREVENT_CREATE: no
    pytest_maxfail: 1

  - tox_description: 'run sanity test cases after disruptive tests'
    tox_envlist: sanity
    tox_step_name: after
    tox_environment:
      TOBIKO_PREVENT_CREATE: no

  - tox_description: 'verify workload resources'
    tox_envlist: scenario
    tox_step_name: verify_resources
    tox_environment:
      TOBIKO_PREVENT_CREATE: yes
