---

test_workflow_steps:
  - tox_description: 'create workload resources'
    tox_envlist: scenario
    tox_step_name: create_resources
    tox_environment:
      TOBIKO_PREVENT_CREATE: no
    test_flaky: true

  - tox_description: 'run sanity test cases before disruptive test cases'
    tox_envlist: sanity
    tox_step_name: before_faults
    tox_environment:
      TOBIKO_PREVENT_CREATE: no
    test_flaky: true

  - tox_description: 'run disruptive test cases'
    tox_envlist: faults
    tox_step_name: faults
    tox_environment:
      TOBIKO_PREVENT_CREATE: no
    test_flaky: true

  - tox_description: 'run sanity test cases after disruptive test cases'
    tox_envlist: sanity
    tox_step_name: after_faults
    tox_environment:
      TOBIKO_PREVENT_CREATE: no
    test_flaky: true

  - tox_description: 'verify workload resources'
    tox_envlist: scenario
    tox_step_name: verify_resources
    tox_environment:
      TOBIKO_PREVENT_CREATE: yes
    test_flaky: true
