---

- name: "find for collected files in '{{ test_collect_dir }}'"
  find:
    paths:
      - "{{ test_collect_dir }}"
    patterns:
      - "tobiko.conf"
      - "tobiko.log"
      - "{{ test_report_name }}*.log"
      - "{{ test_report_name }}*.subunit"
      - "{{ test_report_name }}*.html"
      - "{{ test_report_name }}*.xml"
  register: find_collected_files


- name: "set collected_files fact"
  set_fact:
    collected_files: >
      {{ find_collected_files.files |
         map(attribute='path') |
         map('basename') |
         list }}


- block:
    - name: "check collected files"
      assert:
        that:
          - item in collected_files
      loop:
        - tobiko.log
        - tobiko.conf
        - '{{ test_report_name }}.log'
        - '{{ test_report_name }}.html'
        - '{{ test_report_name }}.subunit'
        - '{{ test_report_name }}.xml'

  rescue:
    - debug: var=collected_files
      failed_when: yes
