- name: Set up Overcloud resources create ssh keys
  shell: |
    test -f ~/.ssh/id_rsa||ssh-keygen -f ~/.ssh/id_rsa -P ''

- name: Create tobiko configuration file
  template:
      src: "templates/tobiko.conf.j2"
      dest: "{{ test.dir }}/tobiko.conf"
      mode: 0755

- name: Set permissive quotas for instances and cores
  shell: |
   source "{{ test.overcloudrc }}"
   openstack quota set --instances -1 admin
   openstack quota set --cores -1 admin
